import type { ClubState } from './types'

export const demoClubState: ClubState = {
  name: 'BTC Alpha Room',
  leaderName: 'Linh Quant',
  activeRound: {
    id: 'ROUND-042',
    market: 'BTC/USD 5m',
    btcSpot: 68421.8,
    direction: 'UP',
    strike: 68600,
    expiryLabel: '14:35 UTC',
    expiryMinutes: 18,
    totalPledgedDusdc: 12840,
    fundingDusdc: 9840,
    fundingTargetDusdc: 15000,
    risk: 'warning',
    status: 'funding',
    thesis:
      'Box Flip reclaimed the prior range high while order flow shifted positive. Execute only if oracle status remains healthy and funding reaches the minimum pool.',
    oracle: 'Pyth BTC/USD',
    suggestedDusdc: 250,
    signalBias: 'bullish',
    confidence: 'Medium',
    indicators: [
      { id: 'box', name: 'Box Flip', state: 'bullish', value: 'Breakout + retest', confidence: 84 },
      { id: 'smc', name: 'Smart Money', state: 'bullish', value: 'BOS confirmed', confidence: 77 },
      { id: 'ma', name: 'MA Trend', state: 'bullish', value: 'EMA stack up', confidence: 72 },
      { id: 'rsi', name: 'RSI', state: 'neutral', value: '61.4 cooling', confidence: 55 },
      { id: 'flow', name: 'Order Flow', state: 'bullish', value: '+1.8M delta', confidence: 69 },
      { id: 'vp', name: 'Volume Profile', state: 'neutral', value: 'Near HVN', confidence: 58 },
    ],
  },
  members: [
    {
      id: 'm1',
      name: 'Linh Quant',
      wallet: '0xA19...74C',
      role: 'leader',
      state: 'accepted',
      pledgedDusdc: 1800,
      accepted: true,
    },
    {
      id: 'm2',
      name: 'Minh',
      wallet: '0xF38...AA2',
      role: 'member',
      state: 'pledged',
      pledgedDusdc: 900,
      accepted: false,
    },
    {
      id: 'm3',
      name: 'Nora',
      wallet: '0xB44...19E',
      role: 'member',
      state: 'executed',
      pledgedDusdc: 1250,
      accepted: true,
    },
    {
      id: 'm4',
      name: 'Duy',
      wallet: '0x91D...C7F',
      role: 'member',
      state: 'watching',
      pledgedDusdc: 0,
      accepted: false,
    },
  ],
  fundingCards: [
    {
      route: 'ready-with-dusdc',
      title: 'Ready with DUSDC',
      description: 'Join immediately when wallet has enough DUSDC for the suggested amount.',
      status: 'ready',
      action: 'Use Balance',
    },
    {
      route: 'deepbook-sui-to-usdc',
      title: 'Swap SUI to USDC',
      description: 'Use DeepBook liquidity first when the wallet only has SUI and needs USDC.',
      status: 'available',
      action: 'Preview Swap',
    },
    {
      route: 'scallop-borrow-usdc',
      title: 'Borrow USDC',
      description: 'Borrow USDC with SUI collateral and show health factor before execution.',
      status: 'needs-review',
      action: 'Review Borrow',
    },
    {
      route: 'bridge-assets-to-sui',
      title: 'Bridge Assets',
      description: 'Route external assets into Sui before joining a prediction round.',
      status: 'available',
      action: 'Open Bridge',
    },
    {
      route: 'club-escrow-usdc-to-dusdc',
      title: 'Club Escrow',
      description: 'Exchange USDC for DUSDC with a leader or member through a time-boxed offer.',
      status: 'available',
      action: 'Find Offer',
    },
  ],
  escrowOffers: [
    {
      id: 'ESC-9182',
      maker: 'Linh Quant',
      offerAsset: 'DUSDC',
      wantAsset: 'USDC',
      offerAmount: 2000,
      wantAmount: 1996,
      expiry: '22m',
      roundId: 'ROUND-042',
      status: 'open',
    },
    {
      id: 'ESC-9183',
      maker: 'Nora',
      offerAsset: 'USDC',
      wantAsset: 'DUSDC',
      offerAmount: 780,
      wantAmount: 776,
      expiry: '1h 08m',
      roundId: 'ROUND-042',
      status: 'reserved',
    },
  ],
  history: [
    {
      id: 'ROUND-041',
      direction: 'DOWN',
      strike: 'BTC < 68120',
      result: 'won',
      pnlDusdc: 1420,
      thesis: 'Failed range reclaim after order-flow exhaustion.',
      participants: 13,
      claimStatus: 'claimed',
      risk: 'ready',
      signalBias: 'bearish',
      confidence: 'High',
      indicatorReasons: [
        'Order Flow: -2.1M delta (bearish, 82%)',
        'Smart Money: BOS failed (bearish, 78%)',
        'RSI: 42.8 fading (bearish, 70%)',
      ],
      riskChecks: [
        { id: 'oracle-health', label: 'Oracle health', passed: true, severity: 'blocking' },
        { id: 'expiry-safe', label: 'Expiry safe', passed: true, severity: 'blocking' },
        { id: 'signal-bias', label: 'Signal consensus', passed: true, severity: 'blocking' },
        { id: 'dusdc-balance', label: 'DUSDC ready', passed: true, severity: 'warning' },
      ],
      confirmedAt: Date.now() - 86_400_000,
    },
    {
      id: 'ROUND-040',
      direction: 'RANGE',
      strike: '67900 - 68500',
      result: 'lost',
      pnlDusdc: -860,
      thesis: 'Expected HVN chop; breakout invalidated the range.',
      participants: 9,
      claimStatus: 'none',
      risk: 'warning',
      signalBias: 'neutral',
      confidence: 'Medium',
      indicatorReasons: [
        'Volume Profile: At POC (neutral, 68%)',
        'Box Flip: Range intact (neutral, 63%)',
        'Basis (Fwd-Spot): Flat basis (neutral, 60%)',
      ],
      riskChecks: [
        { id: 'oracle-health', label: 'Oracle health', passed: true, severity: 'blocking' },
        { id: 'expiry-safe', label: 'Expiry safe', passed: true, severity: 'blocking' },
        { id: 'signal-bias', label: 'Signal consensus', passed: true, severity: 'blocking' },
        {
          id: 'dusdc-balance',
          label: 'DUSDC ready',
          passed: false,
          severity: 'warning',
          message: 'Some members funded late before execution',
        },
      ],
      confirmedAt: Date.now() - 172_800_000,
    },
  ],
  claims: [
    { id: 'CLM-041', roundId: 'ROUND-041', amountDusdc: 188.4, status: 'ready' },
    { id: 'CLM-039', roundId: 'ROUND-039', amountDusdc: 42.1, status: 'waiting' },
  ],
}
