// Plugin Registry — Single source of truth for all available plugins
// Maps plugin IDs to metadata + build paths

import type { PluginMeta } from './types'

/** Resolve plugin JS path based on environment */
export const pluginPath = (name: string) =>
  import.meta.env.DEV
    ? `${import.meta.env.BASE_URL}plugins/${name}/plugin.tsx`
    : `${import.meta.env.BASE_URL}assets/plugins/${name}.js`

/** Complete plugin registry */
export const PLUGIN_REGISTRY: PluginMeta[] = [
  // ── Wallet ──
  {
    id: 'sui-wallet',
    name: 'Sui Wallet',
    description: 'View balances, tokens & transaction history',
    category: 'wallet',
    tags: ['wallet', 'balance', 'tokens'],
    author: 'core',
    version: '1.0.0',
    icon: 'Wallet',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-wallet-profile',
    name: 'Wallet Profile',
    description: 'Profile header with wallet connection & network selector',
    category: 'wallet',
    tags: ['profile', 'wallet', 'connect'],
    author: 'core',
    version: '1.0.0',
    icon: 'UserCircle',
    requiresSui: true,
    defaultSize: { w: 2, h: 1 },
  },
  {
    id: 'sui-create-wallet',
    name: 'Create Wallet',
    description: 'Generate Secp256k1 keypairs for Sui',
    category: 'wallet',
    tags: ['keypair', 'generate', 'security'],
    author: 'core',
    version: '1.0.0',
    icon: 'KeyRound',
    requiresSui: false,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-dual-wallet',
    name: 'Dual Wallet',
    description: 'Connect & compare 2 wallets side by side',
    category: 'wallet',
    tags: ['dual', 'compare', 'multi-wallet'],
    author: 'core',
    version: '1.0.0',
    icon: 'Columns2',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-zk-login',
    name: 'ZK Login',
    description: 'Zero-knowledge proof authentication for Sui',
    category: 'wallet',
    tags: ['zk', 'login', 'auth', 'privacy'],
    author: 'core',
    version: '1.0.0',
    icon: 'Fingerprint',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },

  // ── DeFi ──
  {
    id: 'sui-swap',
    name: 'Token Swap',
    description: 'Swap tokens on Sui DEX',
    category: 'defi',
    tags: ['swap', 'dex', 'trade'],
    author: 'core',
    version: '1.0.0',
    icon: 'ArrowLeftRight',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-wal-swap',
    name: 'WAL Swap',
    description: 'Swap WAL tokens',
    category: 'defi',
    tags: ['swap', 'wal', 'walrus'],
    author: 'core',
    version: '1.0.0',
    icon: 'Repeat',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-lending',
    name: 'Lending Pools',
    description: 'Scallop lending markets — supply & borrow',
    category: 'defi',
    tags: ['lending', 'scallop', 'borrow', 'supply'],
    author: 'core',
    version: '1.0.0',
    icon: 'Landmark',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-payment',
    name: 'Payment',
    description: 'Send SUI payments with memo',
    category: 'defi',
    tags: ['payment', 'send', 'transfer'],
    author: 'core',
    version: '1.0.0',
    icon: 'Send',
    requiresSui: true,
    defaultSize: { w: 2, h: 1 },
  },
  {
    id: 'sui-pool-explorer',
    name: 'Pool Explorer',
    description: 'Browse & analyze DeepBook liquidity pools',
    category: 'defi',
    tags: ['pool', 'deepbook', 'liquidity'],
    author: 'core',
    version: '1.0.0',
    icon: 'Search',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-price-feed',
    name: 'Price Feed',
    description: 'Real-time token prices from Sui oracles',
    category: 'defi',
    tags: ['price', 'oracle', 'feed', 'realtime'],
    author: 'core',
    version: '1.0.0',
    icon: 'TrendingUp',
    requiresSui: true,
    defaultSize: { w: 1, h: 1 },
  },
  {
    id: 'sui-walrus-earn',
    name: 'Walrus Earn',
    description: 'Earn rewards from Walrus storage staking',
    category: 'defi',
    tags: ['walrus', 'earn', 'staking', 'rewards'],
    author: 'core',
    version: '1.0.0',
    icon: 'PiggyBank',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },

  // ── Analytics ──
  {
    id: 'sui-deepbook-orderbook',
    name: 'DeepBook Orderbook',
    description: 'Live orderbook visualization',
    category: 'analytics',
    tags: ['orderbook', 'deepbook', 'trading'],
    author: 'core',
    version: '1.0.0',
    icon: 'BarChart3',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-deepbook-portfolio',
    name: 'DeepBook Portfolio',
    description: 'Track your DeepBook positions & PnL',
    category: 'analytics',
    tags: ['portfolio', 'deepbook', 'pnl'],
    author: 'core',
    version: '1.0.0',
    icon: 'PieChart',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-deepbook-history',
    name: 'Trade History',
    description: 'DeepBook trade history & fills',
    category: 'analytics',
    tags: ['history', 'trades', 'deepbook'],
    author: 'core',
    version: '1.0.0',
    icon: 'History',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-deepbook-analysis',
    name: 'DeepBook Analysis',
    description: 'Advanced market analysis with WASM engine',
    category: 'analytics',
    tags: ['analysis', 'deepbook', 'wasm', 'market'],
    author: 'core',
    version: '1.0.0',
    icon: 'LineChart',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-deepbook-hedging-bot',
    name: 'Hedging Bot',
    description: 'Automated hedging strategies on DeepBook',
    category: 'analytics',
    tags: ['hedging', 'bot', 'automated', 'deepbook'],
    author: 'core',
    version: '1.0.0',
    icon: 'Bot',
    requiresSui: true,
    defaultSize: { w: 2, h: 3 },
  },
  {
    id: 'sui-hedging-monitor',
    name: 'Hedging Monitor',
    description: 'Monitor active hedging positions',
    category: 'analytics',
    tags: ['hedging', 'monitor', 'positions'],
    author: 'core',
    version: '1.0.0',
    icon: 'Activity',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-margin-manager',
    name: 'Margin Manager',
    description: 'Manage margin requirements & collateral',
    category: 'analytics',
    tags: ['margin', 'collateral', 'risk'],
    author: 'core',
    version: '1.0.0',
    icon: 'Shield',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-navi-dashboard',
    name: 'NAVI Dashboard',
    description: 'NAVI protocol overview & positions',
    category: 'analytics',
    tags: ['navi', 'dashboard', 'defi'],
    author: 'core',
    version: '1.0.0',
    icon: 'LayoutDashboard',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-navi-advisor',
    name: 'NAVI Advisor',
    description: 'AI-powered NAVI strategy recommendations',
    category: 'analytics',
    tags: ['navi', 'advisor', 'ai', 'strategy'],
    author: 'core',
    version: '1.0.0',
    icon: 'Lightbulb',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-navi-chatbot',
    name: 'NAVI Chatbot',
    description: 'Chat with AI about NAVI protocol',
    category: 'analytics',
    tags: ['navi', 'chatbot', 'ai'],
    author: 'core',
    version: '1.0.0',
    icon: 'MessageCircle',
    requiresSui: true,
    defaultSize: { w: 2, h: 3 },
  },
  {
    id: 'sui-navi-analysis',
    name: 'NAVI Analysis',
    description: 'Deep analysis of NAVI markets with WASM',
    category: 'analytics',
    tags: ['navi', 'analysis', 'wasm'],
    author: 'core',
    version: '1.0.0',
    icon: 'Microscope',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },

  // ── Social ──
  {
    id: 'sui-link',
    name: 'SuiLink',
    description: 'Cross-chain wallet links & social profile',
    category: 'social',
    tags: ['link', 'social', 'cross-chain'],
    author: 'core',
    version: '1.0.0',
    icon: 'Link',
    requiresSui: true,
    defaultSize: { w: 2, h: 1 },
  },
  {
    id: 'hello-plugin',
    name: 'Hello Plugin',
    description: 'Minimal example plugin — great for learning',
    category: 'utility',
    tags: ['demo', 'example', 'hello'],
    author: 'core',
    version: '1.0.0',
    icon: 'Hand',
    requiresSui: false,
    defaultSize: { w: 1, h: 1 },
  },
  {
    id: 'hello-world-sui',
    name: 'Faucet',
    description: 'Request SUI tokens from testnet faucet',
    category: 'utility',
    tags: ['faucet', 'testnet', 'tokens'],
    author: 'core',
    version: '1.0.0',
    icon: 'Droplets',
    requiresSui: true,
    defaultSize: { w: 1, h: 1 },
  },

  // ── Privacy ──
  {
    id: 'sui-seal-encrypt',
    name: 'Seal Encrypt',
    description: 'Encrypt data with Sui Seal threshold encryption',
    category: 'privacy',
    tags: ['seal', 'encrypt', 'privacy'],
    author: 'core',
    version: '1.0.0',
    icon: 'Lock',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-decrypt',
    name: 'Seal Decrypt',
    description: 'Decrypt Seal-encrypted data',
    category: 'privacy',
    tags: ['seal', 'decrypt', 'privacy'],
    author: 'core',
    version: '1.0.0',
    icon: 'Unlock',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-vault',
    name: 'Seal Vault',
    description: 'Encrypted vault for sensitive data',
    category: 'privacy',
    tags: ['seal', 'vault', 'encrypted', 'storage'],
    author: 'core',
    version: '1.0.0',
    icon: 'ShieldCheck',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-private',
    name: 'Private Messages',
    description: 'End-to-end encrypted messaging on Sui',
    category: 'privacy',
    tags: ['seal', 'private', 'messaging', 'e2e'],
    author: 'core',
    version: '1.0.0',
    icon: 'MessageSquareLock',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-timelock',
    name: 'Timelock',
    description: 'Time-locked encrypted content',
    category: 'privacy',
    tags: ['seal', 'timelock', 'scheduled'],
    author: 'core',
    version: '1.0.0',
    icon: 'Timer',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-allowlist',
    name: 'Allowlist',
    description: 'Manage encrypted content access lists',
    category: 'privacy',
    tags: ['seal', 'allowlist', 'access-control'],
    author: 'core',
    version: '1.0.0',
    icon: 'ListChecks',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-voting',
    name: 'Private Voting',
    description: 'Anonymous on-chain voting with Seal encryption',
    category: 'privacy',
    tags: ['seal', 'voting', 'anonymous', 'governance'],
    author: 'core',
    version: '1.0.0',
    icon: 'Vote',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-zk-merkle',
    name: 'ZK Merkle Proof',
    description: 'Zero-knowledge merkle tree proofs with WASM',
    category: 'privacy',
    tags: ['zk', 'merkle', 'proof', 'wasm'],
    author: 'core',
    version: '1.0.0',
    icon: 'GitBranch',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },

  // ── Storage ──
  {
    id: 'sui-walrus-upload',
    name: 'Walrus Upload',
    description: 'Upload files to Walrus decentralized storage',
    category: 'storage',
    tags: ['walrus', 'upload', 'storage', 'decentralized'],
    author: 'core',
    version: '1.0.0',
    icon: 'Upload',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-walrus-viewer',
    name: 'Walrus Viewer',
    description: 'Browse & view files stored on Walrus',
    category: 'storage',
    tags: ['walrus', 'viewer', 'browse', 'files'],
    author: 'core',
    version: '1.0.0',
    icon: 'Eye',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-walrus',
    name: 'Seal + Walrus',
    description: 'Encrypted file storage on Walrus via Seal',
    category: 'storage',
    tags: ['seal', 'walrus', 'encrypted', 'storage'],
    author: 'core',
    version: '1.0.0',
    icon: 'FolderLock',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'sui-seal-walrus-upload',
    name: 'Seal Walrus Upload',
    description: 'Upload encrypted files to Walrus',
    category: 'storage',
    tags: ['seal', 'walrus', 'upload', 'encrypted'],
    author: 'core',
    version: '1.0.0',
    icon: 'UploadCloud',
    requiresSui: true,
    defaultSize: { w: 2, h: 2 },
  },

  // ── Prediction ──
  {
    id: 'polymarket',
    name: 'Polymarket',
    description: 'Prediction markets overview & trading',
    category: 'prediction',
    tags: ['polymarket', 'prediction', 'markets'],
    author: 'core',
    version: '1.0.0',
    icon: 'TrendingUp',
    requiresSui: false,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'polymarket-detail',
    name: 'Market Detail',
    description: 'Detailed view of a prediction market',
    category: 'prediction',
    tags: ['polymarket', 'detail', 'market'],
    author: 'core',
    version: '1.0.0',
    icon: 'FileBarChart',
    requiresSui: false,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'polymarket-weather',
    name: 'Weather Markets',
    description: 'Weather-based prediction markets',
    category: 'prediction',
    tags: ['polymarket', 'weather', 'prediction'],
    author: 'core',
    version: '1.0.0',
    icon: 'CloudSun',
    requiresSui: false,
    defaultSize: { w: 2, h: 2 },
  },
  {
    id: 'polymarket-wallet',
    name: 'Polymarket Wallet',
    description: 'Manage Polymarket positions & funds',
    category: 'prediction',
    tags: ['polymarket', 'wallet', 'positions'],
    author: 'core',
    version: '1.0.0',
    icon: 'Wallet2',
    requiresSui: false,
    defaultSize: { w: 2, h: 2 },
  },
]

/** Get plugin metadata by ID */
export function getPluginMeta(id: string): PluginMeta | undefined {
  return PLUGIN_REGISTRY.find((p) => p.id === id)
}

/** Get plugins by category */
export function getPluginsByCategory(category: string): PluginMeta[] {
  return PLUGIN_REGISTRY.filter((p) => p.category === category)
}

/** Search plugins by keyword */
export function searchPlugins(query: string): PluginMeta[] {
  const q = query.toLowerCase()
  return PLUGIN_REGISTRY.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)),
  )
}
